<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $properties = [
            [
                'name' => 'Villa Sunset Ubud',
                'country' => 'Indonesia',
                'city' => 'Ubud',
                'price_property' => 1250000,
                'address' => 'Jalan Raya Ubud No. 99',
                'description' => 'Villa dengan pemandangan sawah dan kolam renang pribadi.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyUbud1.jpeg',
                    'uploads/property/propertyDummy/propertyUbud2.jpeg',
                    'uploads/property/propertyDummy/propertyUbud3.jpeg',
                    'uploads/property/propertyDummy/propertyUbud4.jpeg',
                ]),

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Penginapan Gunung Bromo',
                'country' => 'Indonesia',
                'city' => 'Probolinggo',
                'price_property' => 650000,
                'address' => 'Desa Ngadisari No. 12',
                'description' => 'Penginapan nyaman dekat pintu masuk Taman Nasional Bromo.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyBromo1.jpeg',
                    'uploads/property/propertyDummy/propertyBromo2.jpeg',
                    'uploads/property/propertyDummy/propertyBromo3.jpeg',
                    'uploads/property/propertyDummy/propertyBromo4.jpeg',
                    'uploads/property/propertyDummy/propertyBromo5.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Casa Pantai Bali',
                'country' => 'Indonesia',
                'city' => 'Kuta',
                'price_property' => 850000,
                'address' => 'Jalan Pantai Kuta No. 10',
                'description' => 'Rumah tepi pantai dengan akses langsung ke laut di Bali.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyBali1.jpeg',
                    'uploads/property/propertyDummy/propertyBali2.jpeg',
                    'uploads/property/propertyDummy/propertyBali3.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Retreat Puncak Asri',
                'country' => 'Indonesia',
                'city' => 'Bogor',
                'price_property' => 700000,
                'address' => 'Jalan Raya Puncak KM 17',
                'description' => 'Retreat alami di Puncak dengan suasana sejuk dan asri.',
                'user_id' => 3,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyBogor1.jpeg',
                    'uploads/property/propertyDummy/propertyBogor2.jpeg',
                    'uploads/property/propertyDummy/propertyBogor3.jpeg',
                    'uploads/property/propertyDummy/propertyBogor4.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tropical Hideaway Lombok',
                'country' => 'Indonesia',
                'city' => 'Lombok',
                'price_property' => 900000,
                'address' => 'Jalan Raya Senggigi No. 88',
                'description' => 'Vila tropis tersembunyi, cocok untuk liburan romantis.',
                'user_id' => 3,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyLombok1.jpeg',
                    'uploads/property/propertyDummy/propertyLombok2.jpeg',
                    'uploads/property/propertyDummy/propertyLombok3.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5 inti
            [
                'name' => 'Villa Pantai Jimbaran',
                'country' => 'Indonesia',
                'city' => 'Jimbaran',
                'price_property' => 1850000,
                'address' => 'Jl. Pantai Jimbaran No. 8',
                'description' => 'Villa mewah dengan akses langsung ke pantai.',
                'user_id' => 3,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyJimbaran1.jpeg',
                    'uploads/property/propertyDummy/propertyJimbaran2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Villa Puncak Indah',
                'country' => 'Indonesia',
                'city' => 'Bogor',
                'price_property' => 1300000,
                'address' => 'Jl. Raya Puncak No. 45',
                'description' => 'Villa sejuk di kawasan Puncak dengan taman luas.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyPuncak1.jpeg',
                    'uploads/property/propertyDummy/propertyPuncak2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kost Eksklusif Surabaya',
                'country' => 'Indonesia',
                'city' => 'Surabaya',
                'price_property' => 900000,
                'address' => 'Jl. Ngagel Timur No. 77',
                'description' => 'Kost dengan fasilitas lengkap dan dekat kampus.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertySurabaya1.jpeg',
                    'uploads/property/propertyDummy/propertySurabaya2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guest House Yogyakarta',
                'country' => 'Indonesia',
                'city' => 'Yogyakarta',
                'price_property' => 500000,
                'address' => 'Jl. Malioboro No. 10',
                'description' => 'Penginapan strategis di pusat kota Yogyakarta.',
                'user_id' => 3,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyBromo1.jpeg',
                    'uploads/property/propertyDummy/propertyBromo2.jpeg',
                    'uploads/property/propertyDummy/propertyBromo3.jpeg',
                    'uploads/property/propertyDummy/propertyBromo4.jpeg',
                    'uploads/property/propertyDummy/propertyBromo5.jpeg',
                    'uploads/property/propertyDummy/propertyUbud1.jpeg',
                    'uploads/property/propertyDummy/propertyJogja1.jpeg',
                    'uploads/property/propertyDummy/propertyJogja2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Villa Batu Malang',
                'country' => 'Indonesia',
                'city' => 'Batu',
                'price_property' => 1100000,
                'address' => 'Jl. Oro-oro Ombo No. 21',
                'description' => 'Villa dengan fasilitas keluarga dan udara sejuk.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyUbud1.jpeg',
                    'uploads/property/propertyDummy/propertyBatu1.jpeg',
                    'uploads/property/propertyDummy/propertyBatu2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Penginapan Raja Ampat',
                'country' => 'Indonesia',
                'city' => 'Raja Ampat',
                'price_property' => 2000000,
                'address' => 'Pulau Waigeo No. 3',
                'description' => 'Akomodasi eksotis di tengah keindahan laut Raja Ampat.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyRajaAmpat1.jpeg',
                    'uploads/property/propertyDummy/propertyRajaAmpat2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kamar Harian Makassar',
                'country' => 'Indonesia',
                'city' => 'Makassar',
                'price_property' => 400000,
                'address' => 'Jl. Pettarani No. 33',
                'description' => 'Kamar harian nyaman untuk perjalanan bisnis.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyMakassar1.jpeg',
                    'uploads/property/propertyDummy/propertyMakassar2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Villa Lembang View',
                'country' => 'Indonesia',
                'city' => 'Lembang',
                'price_property' => 1400000,
                'address' => 'Jl. Tangkuban Perahu No. 99',
                'description' => 'Villa dengan pemandangan pegunungan dan udara segar.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyLembang1.jpeg',
                    'uploads/property/propertyDummy/propertyLembang2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Apartment Medan Modern',
                'country' => 'Indonesia',
                'city' => 'Medan',
                'price_property' => 1200000,
                'address' => 'Jl. Gatot Subroto No. 65',
                'description' => 'Apartemen modern di pusat kota Medan.',
                'user_id' => 3,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyMedan1.jpeg',
                    'uploads/property/propertyDummy/propertyMedan2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rumah Sewa Harian Semarang',
                'country' => 'Indonesia',
                'city' => 'Semarang',
                'price_property' => 750000,
                'address' => 'Jl. Pandanaran No. 11',
                'description' => 'Rumah sewa harian cocok untuk keluarga saat liburan.',
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertySemarang1.jpeg',
                    'uploads/property/propertyDummy/propertySemarang2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // property second
            [
                'name' => 'Villa Amed Paradise',
                'country' => 'Indonesia',
                'city' => 'bali',
                'address' => 'Amed, Bali',
                'description' => 'Vila dekat pantai dengan suasana tenang.',
                'price_property' => 1200000,
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyAmed1.jpeg',
                    'uploads/property/propertyDummy/propertyAmed2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kost Exclusive Kemang',
                'country' => 'Indonesia',
                'city' => 'Kemang',
                'address' => 'Jakarta Selatan',
                'description' => 'Kost eksklusif di tengah kota, cocok untuk profesional muda.',
                'price_property' => 2500000,
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyKemang1.jpeg',
                    'uploads/property/propertyDummy/propertyKemang2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rumah Tamu Trawas',
                'country' => 'Indonesia',
                'city' => 'Jawa Timur',
                'address' => 'Trawas, Jawa Timur',
                'description' => 'Penginapan asri dengan pemandangan pegunungan.',
                'price_property' => 750000,
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyJawaTimur1.jpeg',
                    'uploads/property/propertyDummy/propertyJawaTimur2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guest House Palembang',
                'country' => 'Indonesia',
                'city' => 'Palembang',
                'address' => 'Palembang',
                'description' => 'Guest house nyaman dan strategis.',
                'price_property' => 400000,
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyPalembang1.jpeg',
                    'uploads/property/propertyDummy/propertyPalembang2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Villa Sunrise Uluwatu',
                'country' => 'Indonesia',
                'city' => 'Uluwatu',
                'address' => 'Uluwatu, Bali',
                'description' => 'Villa modern dengan view sunrise.',
                'price_property' => 1850000,
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertySunrise1.jpeg',
                    'uploads/property/propertyDummy/propertySunrise2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kost Mahasiswa UGM',
                'country' => 'Indonesia',
                'city' => 'Yogyakarta',
                'address' => 'Yogyakarta',
                'description' => 'Kost nyaman dan murah dekat kampus.',
                'price_property' => 800000,
                'user_id' => 2,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyKosYogya1.jpeg',
                    'uploads/property/propertyDummy/propertyKosYogya2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rumah Singgah Solo',
                'country' => 'Indonesia',
                'city' => 'Solo',
                'address' => 'Solo',
                'description' => 'Penginapan sederhana dan ramah keluarga.',
                'price' => 500000,
                'user_id' => 3,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyRumahSolo1.jpeg',
                    'uploads/property/propertyDummy/propertyRumahSolo2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Villa Dago Hills',
                'country' => 'Indonesia',
                'city' => 'Bandung',
                'address' => 'Bandung',
                'description' => 'Villa eksklusif di kawasan Dago atas.',
                'price_property' => 1600000,
                'user_id' => 3,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyDago1.jpeg',
                    'uploads/property/propertyDummy/propertyDago2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kost Putri Cibubur',
                'country' => 'Indonesia',
                'city' => 'Depok',
                'address' => 'Depok',
                'description' => 'Kost khusus putri dengan keamanan 24 jam.',
                'price_property' => 950000,
                'user_id' => 3,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertyCibubur1.jpeg',
                    'uploads/property/propertyDummy/propertyCibubur2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Homestay Samosir Lake',
                'country' => 'Indonesia',
                'city' => 'Samosir',
                'address' => 'Samosir, Sumut',
                'description' => 'Homestay pinggir Danau Toba dengan view spektakuler.',
                'price_property' => 700000,
                'user_id' => 3,
                'media' => json_encode([
                    'uploads/property/propertyDummy/propertySamosir1.jpeg',
                    'uploads/property/propertyDummy/propertySamosir2.jpeg',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('properties')->insert($properties);
    }
}
